const CountryList=()=>{
	return [
		{"value":"AFG","label":"Afghanistan"},
		{"value":"ALB","label":"Albania"},
		{"value":"DZA","label":"Algeria"},
		{"value":"ARG","label":"Argentina"},
		{"value":"AND","label":"Andorra"},
		{"value":"AZE","label":"Azerbaijan"},
		{"value":"BHS","label":"Bahamas(the)"},
		{"value":"BHR","label":"Bahrain"},
		{"value":"BGD","label":"Bangladesh"},
		{"value":"BRB","label":"Barbados"},
		{"value":"CXR","label":"ChristmasIsland"},
		{"value":"COL","label":"Colombia"},
		{"value":"CUB","label":"Cuba"},
		{"value":"CUW","label":"Curaçao"},
		{"value":"DMA","label":"Dominica"},
		{"value":"GUM","label":"Guam"},
		{"value":"GTM","label":"Guatemala"},
		{"value":"GGY","label":"Guernsey"},
		{"value":"HUN","label":"Hungary"},
		{"value":"ISL","label":"Iceland"},
		{"value":"IND","label":"India"},
		{"value":"MLI","label":"Mali"},
		{"value":"MTQ","label":"Martinique"},
		{"value":"MRT","label":"Mauritania"},
		{"value":"NER","label":"Niger(the)"},
		{"value":"SDN","label":"Sudan(the)"},
		{"value":"SWE","label":"Sweden"},
		{"value":"CHE","label":"Switzerland"},
		{"value":"SYR","label":"SyrianArabRepublic"},
		{"value":"TWN","label":"Taiwan"},
		{"value":"URY","label":"Uruguay"},
		{"value":"ZMB","label":"Zambia"},
		{"value":"ZWE","label":"Zimbabwe"},
		{"value":"ALA","label":"ÅlandIslands"}
	];
}

export default CountryList;
